version: "2"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build:
      dockerfile: ./backend/Dockerfile

    volumes:
      - ./backend:/backend
    command: /bin/sh -c 'npm run start'
    ports:
      - "5001:3000"
    depends_on:
      - mongodb

    stdin_open: true
    tty: true

volumes:
  mongodata: